#! /usr/bin/env python
# -*- coding: utf-8 -*-

def options(opt):
	opt.load('compiler_c')
	opt.load('compiler_cxx')
	opt.load('gnu_dirs')


def configure(conf):
	conf.load('compiler_c')
	conf.load('compiler_cxx')
	conf.load('gnu_dirs')

	if conf.env.CXX_NAME in ('gcc', 'clang'):
		conf.env.CXXFLAGS += [ '-std=c++11' ]
	if conf.env.CC_NAME in ('gcc', 'clang'):
		conf.env.CFLAGS += [ '-std=c99' ]

	conf.check(header_name='iconv.h',
	 features='cxx cxxprogram', mandatory=False)

	conf.check_cfg(package='icu-uc', args="--cflags --libs",
	 uselib_store="ICU", mandatory=False)

	if 'HAVE_ICONV_H=1' in conf.env.DEFINES:
		conf.find_program('iconv')
		if conf.env.ICONV:
			out = conf.cmd_and_log(conf.env.ICONV + ['-l'])
			encodings = out.splitlines()
			for i, enc in enumerate(encodings):
				enc = enc.replace('///', '').replace('//', '').replace('/', '')
				encodings[i] = '"%s"' % enc
			encodings = ", ".join(encodings)
			conf.env.DEFINES_ICONV += ['ICONV_ENCODINGS={%s}' % encodings]

	if 'HAVE_ICU' in conf.env.define_key:
		pass

def build(bld):
	bld(
	 target='chardet',
	 features='cxx cxxshlib',
	 source=[
	  'chardet.cpp',
	  'chardet-c.cpp',
	 ],
	 use='ICONV ICU',
	 install_path="${LIBDIR}",
	)

	bld.install_files("${PREFIX}/include/libchardet",
	 ['chardet.hpp', 'chardet_pimpl_h.hpp', 'chardet.h'])

	bld(
	 target='chardet-test',
	 features='cxx cxxprogram',
	 source='chardet-test.cpp',
	 use='chardet',
	 rpath='${ORIGIN}',
	 install_path=None,
	)

	bld(
	 target='chardet-c-test',
	 features='c cprogram',
	 source='chardet-c-test.c',
	 use='chardet',
	 rpath='${ORIGIN}',
	 install_path=None,
	)

